# Generated by Django 2.2.3 on 2019-10-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0013_auto_20190927_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='x_coordinate',
            field=models.IntegerField(blank=True, default=-2080, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='y_coordinate',
            field=models.IntegerField(blank=True, default=-165, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='z_coordinate',
            field=models.IntegerField(blank=True, default=5945, null=True),
        ),
    ]
