# Generated by Django 2.2.3 on 2019-10-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0014_auto_20191018_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField(blank=True, default=-2080, null=True)),
                ('y_coordinate', models.IntegerField(blank=True, default=-165, null=True)),
                ('z_coordinate', models.IntegerField(blank=True, default=5945, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='x_coordinate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='y_coordinate',
        ),
        migrations.RemoveField(
            model_name='place',
            name='z_coordinate',
        ),
    ]
