# Generated by Django 2.2.3 on 2019-11-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0016_data_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('x_coordinate', models.IntegerField(blank=True, default=0, null=True)),
                ('y_coordinate', models.IntegerField(blank=True, default=0, null=True)),
                ('z_coordinate', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAdmin',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parkplace.Log')),
            ],
            bases=('parkplace.log',),
        ),
    ]
