# Generated by Django 2.2.3 on 2019-11-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0017_log_logadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogAdmin',
        ),
    ]
