# Generated by Django 2.2.3 on 2020-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0018_delete_logadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='x_coordinate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='y_coordinate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='z_coordinate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
